// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGN9djV0HrC28_CcG4Wcfnwc1M0zlpRk',
    appId: '1:830678219852:android:ff2985d1334da5ce59c8e9',
    messagingSenderId: '830678219852',
    projectId: 'ketub-platform',
    storageBucket: 'ketub-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXNE6ynBLbEAgdu9oWXlQwRR_FboWWV8',
    appId: '1:830678219852:ios:8b089d57eb86bef159c8e9',
    messagingSenderId: '830678219852',
    projectId: 'ketub-platform',
    storageBucket: 'ketub-platform.appspot.com',
    androidClientId: '830678219852-jb7m9sq3ukcp6jht89tprpgi1ul58k91.apps.googleusercontent.com',
    iosClientId: '830678219852-l8dcdn0i7v6vivb8cep0ohtjt3t2mgjp.apps.googleusercontent.com',
    iosBundleId: 'com.papyrus.mehdok.hobbollahcom',
  );
}
