name: Flutter CI/CD

on:
  push:
    branches: [ "config/nosos" ]
  pull_request:
    branches: [ "config/nosos" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
          java-version: '11'       # Use Java 11

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Make sure this version is compatible with your project

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
